-- Demo question bank. Run AFTER schema.sql.
insert into public.questions (unit, lesson, difficulty, prompt, options, answer, explanation) values
('unit-5','Linear inequalities','Easy','Solve: 3x + 5 > 14.','["x > 3", "x < 3", "x > 9/2", "x < 9/2"]'::jsonb,0,'Subtract 5 and divide by 3: x > 3.'),
('unit-5','Linear inequalities','Medium','Solve: -2x + 7 ≤ 15.','["x ≤ -4", "x ≥ -4", "x ≤ 4", "x ≥ 4"]'::jsonb,1,'Dividing by -2 reverses the inequality.'),
('unit-5','Solving systems of linear inequalities graphically','Medium','Which point satisfies x + y ≤ 6 and x ≥ 2?','["(1,4)", "(2,4)", "(3,5)", "(0,0)"]'::jsonb,1,'(2,4) gives 6 ≤ 6 and 2 ≥ 2.'),
('unit-5','Solving systems of linear inequalities graphically','Easy','For y > 2x - 1, the boundary line is drawn as:','["A solid line", "A dashed line", "A vertical line", "A horizontal line"]'::jsonb,1,'A strict inequality uses a dashed boundary.'),
('unit-5','Linear programming and optimization','Medium','In linear programming, the maximum or minimum of a linear objective over a bounded polygonal feasible region occurs at:','["Any point on the x-axis", "A corner (vertex) of the feasible region", "Only the origin", "The midpoint of the region"]'::jsonb,1,'An optimum occurs at a vertex.'),
('unit-5','Linear programming and optimization','Hard','Maximize P = 3x + 2y subject to x ≥ 0, y ≥ 0, x + y ≤ 4. What is the maximum P?','["8", "10", "12", "16"]'::jsonb,2,'Check vertices (0,0), (4,0), (0,4): P = 0, 12, 8.'),
('unit-5','Inverse function','Easy','If f(x) = 2x + 3, then f⁻¹(x) is:','["(x + 3)/2", "(x - 3)/2", "2x - 3", "3 - 2x"]'::jsonb,1,'Swap x and y, then solve.'),
('unit-5','Inverse function','Medium','If f(5) = 12, then f⁻¹(12) =','["5", "7", "12", "60"]'::jsonb,0,'Inverse functions reverse the input-output pair.'),
('unit-5','Solving exponential equations','Easy','Solve 2^x = 16.','["2", "3", "4", "8"]'::jsonb,2,'16 = 2^4.'),
('unit-5','Solving exponential equations','Medium','Solve 3^(x+1) = 27.','["1", "2", "3", "4"]'::jsonb,1,'27 = 3^3, so x = 2.'),
('unit-5','The logarithmic function','Easy','Evaluate log₁₀(1000).','["1", "2", "3", "10"]'::jsonb,2,'10^3 = 1000.'),
('unit-5','The logarithmic function','Medium','If log₂(x) = 5, then x =','["10", "16", "25", "32"]'::jsonb,3,'x = 2^5 = 32.'),
('unit-5','Some Properties of logarithms','Medium','Simplify: log(a) + log(b), for positive a and b.','["log(a+b)", "log(ab)", "log(a/b)", "log(a-b)"]'::jsonb,1,'Product rule.'),
('unit-5','Some Properties of logarithms','Medium','Simplify: log(a) - log(b), for positive a and b.','["log(ab)", "log(a+b)", "log(a/b)", "log(b/a)"]'::jsonb,2,'Quotient rule.'),
('unit-5','Revision and unit test','Medium','Which statement is true for every positive x and base b > 0, b ≠ 1?','["log_b(x)=b^x", "log_b(b^x)=x", "log_b(x)=x^b", "log_b(1)=1"]'::jsonb,1,'Logarithms and exponentials are inverse operations.'),
('unit-5','Revision and unit test','Hard','Solve: log₂(x - 1) = 3.','["7", "8", "9", "10"]'::jsonb,2,'x - 1 = 8, so x = 9.'),
('unit-6','Trigonometric identities','Easy','Which identity is always true?','["sin²θ + cos²θ = 1", "sinθ + cosθ = 1", "tanθ = sinθ·cosθ", "sin²θ - cos²θ = 1"]'::jsonb,0,'Fundamental Pythagorean identity.'),
('unit-6','Trigonometric identities','Medium','tanθ can be written as:','["cosθ/sinθ", "sinθ/cosθ", "1/sinθ", "1/cosθ"]'::jsonb,1,'tanθ = sinθ/cosθ.'),
('unit-6','Solving Trigonometric equations','Medium','For 0° ≤ θ ≤ 360°, solve sinθ = 0.','["0° only", "180° only", "0° and 180°", "0°, 180°, and 360°"]'::jsonb,3,'Sine is zero at multiples of 180° in the interval.'),
('unit-6','Solving Trigonometric equations','Easy','For 0° ≤ θ ≤ 360°, cosθ = 1 at:','["0° and 360°", "90°", "180°", "270°"]'::jsonb,0,'Cosine equals 1 at 0° and 360° in the closed interval.'),
('unit-6','The sine law and the cosine law','Medium','The sine law relates sides and their opposite angles. Which form is correct?','["a/sin A = b/sin B = c/sin C", "a cos A = b cos B", "a/sin B = b/sin A", "a+b=c"]'::jsonb,0,'Sine law.'),
('unit-6','The sine law and the cosine law','Medium','Which is the cosine law?','["a²=b²+c²-2bc cos A", "a=b+c", "a²=b²+c²+2bc sin A", "a/sin A=b/sin B"]'::jsonb,0,'Cosine law.'),
('unit-6','Solving triangle','Easy','The sum of the interior angles of any triangle is:','["90°", "180°", "270°", "360°"]'::jsonb,1,'Triangle angles add to 180°.'),
('unit-6','Solving triangle','Medium','If A = 50° and B = 60° in a triangle, C =','["60°", "70°", "80°", "90°"]'::jsonb,1,'C = 70°.'),
('unit-6','Applications on solving triangle','Medium','A 10 m ladder makes a 60° angle with the ground. Approximately how high does it reach?','["5 m", "8.66 m", "10 m", "17.32 m"]'::jsonb,1,'10 sin60° ≈ 8.66 m.'),
('unit-6','Applications on solving triangle','Hard','Two sides of a triangle are 5 m and 7 m with included angle 60°. The third side is approximately:','["3.46 m", "6.24 m", "8.49 m", "12 m"]'::jsonb,1,'c²=39, so c≈6.24.'),
('unit-6','Trigonometric functions of the Sum and the difference of two angles','Medium','sin(A+B) equals:','["sinA cosB + cosA sinB", "sinA sinB + cosA cosB", "sinA cosB - cosA sinB", "cosA cosB - sinA sinB"]'::jsonb,0,'Sine addition formula.'),
('unit-6','Trigonometric functions of the Sum and the difference of two angles','Medium','cos(A-B) equals:','["cosA cosB + sinA sinB", "cosA cosB - sinA sinB", "sinA cosB + cosA sinB", "sinA sinB - cosA cosB"]'::jsonb,0,'Cosine difference formula.'),
('unit-6','Trigonometric functions of double an angle','Medium','sin(2A) equals:','["sin²A", "2sinA cosA", "2cos²A", "sinA + cosA"]'::jsonb,1,'Double-angle identity.'),
('unit-6','Trigonometric functions of double an angle','Medium','cos(2A) can be written as:','["2sinA cosA", "cos²A - sin²A", "sin²A + cos²A", "2sin²A - 1"]'::jsonb,1,'One standard form.'),
('unit-6','Revision and unit test','Hard','If sinθ = 3/5 and θ is acute, cosθ =','["3/5", "4/5", "5/4", "1/5"]'::jsonb,1,'Pythagorean identity gives 4/5.'),
('unit-6','Revision and unit test','Hard','If A=30°, B=45°, then sin(A+B) =','["√2/2", "√3/2", "(√6+√2)/4", "1/2"]'::jsonb,2,'sin75° = (√6+√2)/4.')
ON CONFLICT DO NOTHING;
